name: frontend
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Create bundle
        working-directory: ./frontend
        run: npm run build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/investment:latest
  deploy :
    name: "Deploy Docker image to aws"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: echo "Start deploy container"