name: frontend
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Create bundle
        working-directory: ./frontend
        run: npm run build