name: frontend
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Create bundle
        working-directory: ./frontend
        run: npm run build